stages:
  - Lint
  - test
  - build
  - deploy

dependency-scanning:
  stage: Lint
  image: pipelinecomponents/php-security-checker:latest
  script:
    - cd ${COMPOSER_LOCATION:-.} && security-checker security:check composer.lock
    - rm composer.lock
  allow_failure: true
  except:
    - staging
    - master

phpunit:
  stage: test
  services:
    - name: mysql:8.0
      command: ["--default-authentication-plugin=mysql_native_password"]
  environment:
    name: test
    url: https://test.example.com
  script:
    - php -v
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak
    - echo "" | sudo tee /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - mysql --host="${DB_HOST}" --user="${MYSQL_USER}" --password="${MYSQL_PASSWORD}" "${MYSQL_DATABASE}" < db.sql
    - ./vendor/phpunit/phpunit/phpunit --version
    - php -d short_open_tag=off ./vendor/phpunit/phpunit/phpunit -v --colors=never --stderr
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  only: 
    - master
    - staging
 